YuLung/urls.py
from django.http import HttpResponse
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth import logout
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetCompleteView
)
from django.contrib.sitemaps.views import sitemap
from YuLung.sitemaps import StaticSitemap
from reservation.sitemaps import ServiceSitemap
from django.conf import settings
from django.conf.urls.static import static
from . import views

sitemaps = {
    'static': StaticSitemap,
    'service': ServiceSitemap
}

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^reservation/', include('reservation.urls')),
    re_path(r'^comments/$', views.Comments.as_view(), name='comments'),
    re_path(r'^my_reservation/$', views.MyReservation.as_view(), name='my_reservation'),
    re_path(r'^signin/$', views.SignIn.as_view(), name='sign-in'),
    re_path(r'^signup/$', views.SignUp.as_view(), name='sign-up'),
    re_path(r'^#_=_login/success/$', views.loginSuccess, name='login-success'),
    re_path(r'^login/success/$', views.loginSuccessRedirect, name='login-success-redirect'),
    re_path(r'^faq/$', views.FAQpage.as_view(), name='faq'),
    re_path(r'^privacy/$', views.privacy, name='privacy'),
    re_path(r'^tos/$', views.tos, name='tos'),
    re_path(r'^my/$', views.MyPage.as_view(), name='my'),
    re_path(r'^user/personalinfo/$',
            views.UserInfo.as_view(),
            name='user-profile'),
    re_path(r'^password/reset/$',
            views.PasswordReset.as_view(),
            name='front_password_reset'),
    re_path(r'^password_reset/done/$',
            PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
            name='front_password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.PasswordResetConfirm.as_view(),
            name='front_password_reset_confirm'),
    re_path(r'^reset/done/$',
            PasswordResetCompleteView.as_view(template_name='password_set_complete.html'),
            name='front_password_reset_complete'),
    re_path(r'^logou/$', logout, name='logout'),
    # Site Admin
    re_path(r'^site_admin/$', views.AdminIndex.as_view(), name='admin-index'),
    re_path(r'^site_admin/login/$', views.AdminSignIn.as_view(), name='admin-login'),
    re_path(r'^site_admin/logout/$', views.adminLogout, name='admin-logout'),
    re_path(r'^site_admin/info/banner/$', views.AdminBanner.as_view(), name='admin-banner'),
    re_path(r'^site_admin/password/reset/$',
            views.AdminPasswordReset.as_view(),
            name='password_reset'),
    re_path(r'^site_admin/password_reset/done/$',
            PasswordResetDoneView.as_view(template_name='admin_site/password_reset_done.html'),
            name='password_reset_done'),
    re_path(r'^site_admin/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.AdminPasswordResetConfirm.as_view(),
            name='password_reset_confirm'),
    re_path(r'^site_admin/reset/done/$',
            PasswordResetCompleteView.as_view(template_name='admin_site/password_set_complete.html'),
            name='password_reset_complete'),
    re_path(r'^site_admin/info/faq/$', views.AdminFAQ.as_view(), name='admin-faq'),
    re_path(r'^site_admin/info/faq/new/$', views.AdminFAQCreate.as_view(), name='admin-faq-create'),
    re_path(r'^site_admin/info/faq/(?P<pk>[0-9]+)/$',
            views.AdminFAQEdit.as_view(),
            name='admin-faq-edit'),
    re_path(r'^site_admin/info/faq/(?P<pk>[0-9]+)/delete/$',
            views.adminFAQDelete,
            name='admin-faq-delete'),
    re_path(r'^site_admin/info/settings/$', views.AdminSiteInfo.as_view(), name='admin-siteinfo'),
    re_path(r'^site_admin/info/seo/$', views.AdminSEO.as_view(), name='admin-seo'),
    re_path(r'^site_admin/info/email', views.AdminEmailTemplate.as_view(), name='admin-email'),
    re_path(r'^site_admin/service/course/$', views.AdminService.as_view(), name='admin-service'),
    re_path(r'^site_admin/service/course/new/$',
            views.AdminServiceCreate.as_view(),
            name='admin-service-create'),
    re_path(r'^site_admin/service/course/(?P<pk>[0-9]+)/$',
            views.AdminServiceEdit.as_view(),
            name='admin-service-edit'),
    re_path(r'^site_admin/service/course/(?P<pk>[0-9]+)/delete/$',
            views.adminServiceDelete,
            name='admin-service-delete'),
    re_path(r'^site_admin/service/customer/$', views.AdminCustomer.as_view(), name='admin-customer'),
    re_path(r'^site_admin/service/customer/new/$',
            views.AdminCustomerCreate.as_view(),
            name='admin-customer-create'),
    re_path(r'^site_admin/service/customer/(?P<pk>[0-9]+)/$',
            views.AdminCustomerEdit.as_view(),
            name='admin-customer-edit'),
    re_path(r'^site_admin/service/customer/(?P<pk>[0-9]+)/delete/$',
            views.adminCustomerDelete,
            name='admin-customer-delete'),
    re_path(r'^site_admin/calendar/$', views.AdminCalendar.as_view(), name='admin-calendar'),
    re_path(r'^site_admin/calendar/time_slot/$', views.AdminTimeSlot.as_view(), name='admin-timeslot'),
    re_path(r'^site_admin/calendar/time_slot/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$',
            views.AdminTimeSlot.as_view(),
            name='admin-timeslot-date'),
    re_path(r'^site_admin/calendar/time_slot/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/edit/(?P<pk>[0-9]+)/$',
            views.AdminTimeSlotEdit.as_view(),
            name='admin-timeslot-date-edit'),
    re_path(r'^site_admin/calendar/time_slot/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/delete/(?P<pk>[0-9]+)/$',
            views.adminTimeSlotDelete,
            name='admin-timeslot-date-delete'),
    re_path(r'^site_admin/order/$', views.AdminOrder.as_view(), name='admin-order'),
    re_path(r'^site_admin/ticket/$', views.AdminTicket.as_view(), name='admin-ticket'),
    re_path(r'^site_admin/comment/$', views.AdminComment.as_view(), name='admin-comment'),
    re_path(r'^site_admin/comment/(?P<pk>[0-9]+)/approve/$', views.adminCommentApprove, name='admin-comment-approve'),
    re_path(r'^site_admin/comment/(?P<pk>[0-9]+)/disapprove/$',
            views.adminCommentDisapprove,
            name='admin-comment-disapprove'),
    re_path(r'^site_admin/comment/(?P<pk>[0-9]+)/delete/$', views.adminCommentDelete, name='admin-comment-delete'),
    re_path(r'^site_admin/statistic/$', views.AdminStatistic.as_view(), name='admin-statistic'),
    re_path(r'^site_admin/data_export/$', views.AdminDataExport.as_view(), name='admin-data'),
    re_path(r'^site_admin/user_account/$', views.AdminUserAccount.as_view(), name='admin-user-account'),
    re_path(r'^site_admin/user_profile/$', views.AdmonUserProfile.as_view(), name='admin-user-profile'),
    re_path(r'^site_admin/user_permission/$', views.AdminUserPermission.as_view(), name='admin-user-permission'),
    # AJAX
    re_path(r'ajax/order/$', views.getOrderDetails, name='ajax-get-order'),
    re_path(r'ajax/ticket/$', views.getTicketDetails, name='ajax-get-ticket'),
    re_path(r'ajax/check_dayrender', views.check_adminDayRender, name='ajax-admin-dayrender'),
    re_path(r'ajax/get_user_ticket', views.adminGetUserTicket, name='ajax-admin-get-ticket'),
    re_path(r'ajax/search_ticket/$', views.adminSearchTicket, name='ajax-admin-search-ticket'),
    re_path(r'ajax/get_barchart/$', views.adminGetBarChart, name='ajax-admin-get-barchart'),
    re_path(r'ajax/get_piechart/$', views.adminGetPieChart, name='ajax-admin-get-piechart'),
    re_path(r'ajax/get_service_lines/$', views.adminGetLineChartService, name='ajax-admin-get-service-lines'),
    re_path(r'ajax/get_custerm_lines/$', views.adminGetLineChartCustomer, name='ajax-admin-get-customer-lines'),
    re_path(r'ajax/get_income_lines/$', views.adminGetLineChartIncome, name='ajax-admin-get-income-lines'),
    re_path(r'ajax/get_user/$', views.adminGetUserAccount, name='ajax-admin-get-user-account'),
    re_path(r'ajax/edit_user/$', views.adminUserAccountEdit, name='ajax-admin-user-account-edit'),
    re_path(r'ajax/del_user/$', views.adminUserAccountDelete, name='ajax-admin-user-account-del'),
    re_path(r'ajax/update_faq_order/$', views.adminUpdateFAQOrder, name='ajax-admin-update-faq-order'),
    re_path(r'ajax/get_record_count/$', views.adminGetRecordCount, name='ajax-admin-get-record-count'),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^googlee431d29ab682695b\.html$',
            lambda r: HttpResponse("google-site-verification: googlee431d29ab682695b.html", content_type="text/plain")),
    re_path(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: ", content_type="text/plain")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import re_path
from . import views

app_name = 'reservation'

urlpatterns = [
    re_path(r'^$', views.Reservation.as_view(), name='reservation-index'),
    re_path(r'^(?P<customer_pk>[0-9]+)/service/$', views.Service.as_view(), name='reservation-service'),
    re_path(r'^(?P<customer_pk>[0-9]+)/(?P<service_pk>[0-9]+)/date/$', views.Date.as_view(), name='reservation-date'),
    re_path(r'^(?P<customer_pk>[0-9]+)/(?P<service_pk>[0-9]+)/(?P<timeslot_pk>[0-9]+)/info/$',
            views.Info.as_view(),
            name='reservation-info'),
    re_path(r'^(?P<order_pk>[0-9]+)/confirm/$', views.Confirm.as_view(), name='reservation-confirm'),
    re_path(r'^(?P<order_pk>[0-9]+)/details/$', views.Confirm.as_view(), name='reservattion-order-details'),
    re_path(r'^service/(?P<service_pk>[0-9]+)/detail/$', views.ServiceDetail.as_view(), name='service-detail'),
    re_path(r'^cancelreservation/(?P<order_pk>[0-9]+)/$', views.cancel_reservation, name='reservation-cancel'),
    re_path(r'^site_admin/order/cancelreservation/(?P<order_pk>[0-9]+)/$',
            views.admin_cancel_reservation,
            name='admin-reservation-cancel'),
    re_path(r'^site_admin/order/ticket/cancelreservation/(?P<ticket_pk>[0-9]+)/$',
            views.admin_cancel_ticket_reservation,
            name='admin-ticket-reservation-cancel'),
    re_path(r'^sendvalidation_email/(?P<order_pk>[0-9]+)/$',
            views.send_validation_email,
            name='reservation-send-email'),
    re_path(r'^sendvalidation_sms/(?P<order_pk>[0-9]+)/$', views.send_validation_sms, name="reservation-send-sms"),
    re_path(r'^sendvalidation_success/$', views.send_validation_success, name='reservation-send-success'),
    re_path(r'^confirm_reservation/(?P<validation_key>[\w]+)/$',
            views.confirm_reservation,
            name='reservation-confirm-reservation'),
    re_path(r'^ajax/dayrender/', views.get_dayrender, name='ajax-dayrender'),
    re_path(r'^ajax/dayclick/', views.get_dayclick, name='ajax-dayclick'),
    re_path(r'^ajax/setinputperson/$', views.set_inputperson, name='ajax-inputperson'),
    re_path(r'^gen_ics/(?P<order_pk>[0-9]+)/$', views.GenICS(), name='reservation-genics'),
    re_path(r'^gen_google/(?P<order_pk>[0-9]+)/$', views.genGoogle, name='reservation-gengoogle')
]

YuLung/models.py
import os
from django.db import models
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.core.validators import MinValueValidator, MaxValueValidator, validate_email
from django.conf import settings
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from reservation.models import Orders

bannerfs = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'banners_image'))


class Banner(models.Model):
    banner_image = models.ImageField(upload_to='banners_image')
    banner_description = models.CharField(max_length=255)
    banner_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    title = models.CharField(max_length=255)
    content = models.CharField(max_length=1024)
    star = models.DecimalField(max_digits=2,
                               decimal_places=1,
                               validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    approve = models.BooleanField(default=False)
    active = models.BooleanField(default=False)

    def __unicode__(self):
        if(self.active):
            active = 'Active'
        else:
            active = 'Inactive'
        if len(self.content) > 20:
            content = self.content[0:20] + ' ...'
        else:
            content = self.content[:]
        return active + ' || ' + self.title + '-' + content


class FAQ(models.Model):
    question = models.CharField(max_length=1024)
    answer = RichTextField(max_length=1024)
    priority = models.DecimalField(max_digits=5, decimal_places=3)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    def __unicode__(self):
        if(self.active):
            active = 'Active'
        else:
            active = 'Inactive'
        if len(self.question) > 20:
            question = self.question[0:20] + '...'
        else:
            question = self.question[:]
        return active + ' || ' + question

    def get_absolute_url(self):
        return reverse('faq')


class SiteInfo(models.Model):
    site_info_content = RichTextField(max_length=1024)
    email = models.EmailField(validators=[validate_email])
    phone = models.CharField(max_length=16)
    address = models.CharField(max_length=255)


class Ticket(models.Model):
    assigned_by = models.ForeignKey(User, related_name='%(class)s_assigned_by', on_delete=models.CASCADE, null=True)
    assigned_to = models.ForeignKey(User, related_name='%(class)s_assigned_to', on_delete=models.CASCADE, null=True)
    order = models.ForeignKey(Orders, on_delete=models.CASCADE, null=True)
    finished = models.BooleanField(default=False)
    reported_customer_number = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(0)])
    create_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    reminder = models.TextField(max_length=2048, blank=True, default='')


class SEO(models.Model):
    title = models.CharField(max_length=1024, blank=True, default='')
    url_address = models.URLField(null=True)
    description = models.CharField(max_length=1024, blank=True, default='')
    img = models.ImageField(upload_to='seo_image', blank=True, default='')
    type = models.CharField(default='website', max_length=1024)


class EmailTemplate(models.Model):
    from_email = models.EmailField()
    subject = models.CharField(max_length=1024)
    email_content = models.TextField(max_length=2048)

YuLung/templates/order/cancel_success.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% block title %}You reservation has been cancelled{% endblock %}

{% block meta %} 
{% endblock %}

{% block extraheader %}
{% endblock %}

{% block body %}
<div id="main" class="container mb-3">
  <div id="section" class="row">
    <div class="col-12">
      <div class="card p-3">

            <strong>您的預約已取消，可點擊下列超連結回到我的預約。</strong>
            <a href="{% url 'my_reservation' %}">回到我的預約頁面</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

YuLung/templates/order/confirm.html
{% extends 'base.html' %}

{% block title %}確認預約資料{% endblock %}

{% block meta %}
{% endblock %}

{% block extraheader %}
<script src="https://apis.google.com/js/api.js"></script>
{% endblock %}

{% block body %}
<div id="main" class="container mb-3">
  {% include 'order/order_step_bar.html' with page_name='confirm' %}
  <div id="section" class="row">
    <div class="col-lg-8 mx-auto">
      <div class="shadow card">
        <div class="card-body">
          <div class="h4 text-center">請選擇下列其中一種方式驗證身分，即可完成預約。</div>
	  <div class="row my-4">
            <div class="col-lg-8 mx-auto">
              <div class="row">
                <div class="col-12 col-lg-6 my-1">
                  <a class="validate btn btn-outline-secondary btn-block" value="{{order.pk}}" href="#" onclick="window.open('{% url 'reservation:reservation-send-email' order.pk %}', '_blank', 'location=yes,height=600,width=600,scrollbars=yes,status=yes');">電子郵件確認</a>
                </div>
                <div class="col-12 col-lg-6 my-1">
                  <a class="validate btn btn-outline-secondary btn-block" value="{{order.pk}}" href="#" onclick="window.open('{% url 'reservation:reservation-send-sms' order.pk %}', '_blank', 'location=yes,height=600,width=600,scrollbars=yes,status=yes');">電話簡訊確認</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /#section -->
  <div class="row mt-5 text-center">
    <a class="mx-auto" href="{% url 'my_reservation' %}">查看我的預約</a>
  </div>
</div>
<script>
  $(document).ready(function() {
    var clickEvent = false;
    $('a:not(.validate)').click(function(e) {
      var clickURL = $(this).attr('href');
      e.preventDefault();
      $.ajax({
        url: "{% url 'ajax-get-order' %}",
        data: { 'order_pk': {{order.pk}} },
        success: function (response) {
          //console.log(response);
          if (response.status == 'unconfirmed') {
            alert('提醒您，您尚未完成預約，請選擇使用電子郵件或電話簡訊確認預約行程。');
	  } else {
            $(location).attr('href', clickURL);
          }
        }
      });
    });
  });
</script>
{% endblock %}

YuLung/templates/order/details.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% block title %}確認預約資料{% endblock %}

{% block meta %} 
{% endblock %}

{% block extraheader %}
    <script src="https://apis.google.com/js/api.js"></script>
{% endblock %}

{% block body %}
<!-- <div class="alert alert-info col-9 mx-auto" role="alert">請選擇以手機簡訊或電子郵件方式確認以下預約內容</div>  -->

<div id="main" class="container mb-3">

    {% include 'order/order_step_bar.html' with page_name='confirm'  %}

    <div id="section" class="row">
        <div class="col-12">
                <div class="card p-3">
                    {% if order.status == 'unconfirmed' %}
                    <div class="alert alert-warning col-12 mx-auto" role="alert">請選擇以手機簡訊或電子郵件方式確認以下預約內容</div>
                    {% elif order.status == 'confirmed' %}
                    <div class="alert alert-warning col-12 mx-auto" role="alert">您已完成電子郵件/簡訊確認，請稍候導覽中心同仁確認以完成預約程序</div>
                    {% elif order.status == 'occupy' %}
                    <div class="alert alert-info col-12 mx-auto" role="alert">您已完成預約，請在預約時段前抵達導覽中心，謝謝</div>
                    {% else %}
                    {% endif %}
                    <div class="form-group row">
                        <label class="col-3 col-form-label">預約活動</label>
                        <div class="col-9 font-weight-bold d-flex align-items-center">{{ order.service_type.service_title }}</div>
                    </div>
		    <div class="form-group row">
                        <label class="col-3 col-form-label">姓　　名</label>
                        <div class="col-9 font-weight-bold d-flex align-items-center">{{ order.customer_details.name }}</div>
                    </div>
                    <div class="form-group row">
                        <label class="col-3 col-form-label">電子郵件</label>
                        <div class="col-9 font-weight-bold d-flex align-items-center">{{ order.customer_details.email }}</div>
                    </div>
                    <div class="form-group row">
                        <label class="col-3 col-form-label">行動電話</label>
                        <div class="col-9 font-weight-bold d-flex align-items-center">{{ order.customer_details.phone }}</div>
                    </div>
                    <div class="form-group row">
                        <label class="col-3 col-form-label">聯絡電話</label>
                        <div class="col-9 font-weight-bold d-flex align-items-center">{{ order.customer_details.phone2 }}</div>
                    </div>
                    <div class="form-group row">
                        <label class="col-3">預約日期</label>
                        <div class="col-9 font-weight-bold d-flex align-items-center">{{ order.time_slot.date | date:'Y-m-d' }}</div>
                    </div>
                    <div class="form-group row">
                        <label class="col-3">預約時間</label>
                        <div class="col-9 font-weight-bold d-flex align-items-center">{{ order.time_slot.start_time | date:'H:i' }}</div>
                    </div>
		    <div class="form-group row">
			<label class="col-3">預約人數</label>
			<div class="col-9 font-weight-bold d-flex align-items-center">{{ order.number_of_customer }}</div>
		    </div>
                    <div class="form-group row">
                        <label class="col-3">預約代碼</label>
                        <div class="col-9 font-weight-bold d-flex align-items-center">{{ order.code }}</div>
                    </div>
                    <div class="form-group row">
                        <label class="col-3">預約狀態</label>
                        <div class="col-9 font-weight-bold d-flex align-items-center">
                            {% if order.status == 'unconfirmed' %}
                                <span class="text-danger mr-2">未確認</span>(<a class="sendemail" value="{{ order.pk }}" href="{% url 'reservation:reservation-send-email' order.pk %}">電子郵件確認</a> / <a class="sendsms" value="{{ order.pk }}" href="{% url 'reservation:reservation-send-sms' order.pk %}">電話簡訊確認</a>)
                            {% elif order.status == 'confirmed' %}
                                <span class="text-success">服務人員將與您確認</span>
                            {% elif order.status == 'occupy' %}
                                <span class="text-primary">已確認您的行程</span>
                            {% else %}
                                <span class="text-danger mr-2">STATUS ERROR</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-12 text-right">
                            <a href="{% url 'reservation:reservation-cancel' order.pk %}" class="btn btn-danger">取消預約 <i class="fa fa-calendar-times-o" aria-hidden="true"></i></a>
                            <a href="{% url 'reservation:reservation-index' %}#main" class="btn btn-info">增加預約 <i class="fa fa-calendar-plus-o" aria-hidden="true"></i></a>
                            <a href="{% url 'my_reservation' %}" class="btn btn-outline-info">顯示所有預約 <i class="fa fa-calender-check-o" aria-hidden="true"></i></a>
                        </div>
                    </div>
                    <div class="form-group row mt-3 pt-3 border border-left-0 border-right-0 border-bottom-0">
                        <label class="col-3">添加至日曆</label>
                        <div class="col-9">
                            <a href="{% url 'reservation:reservation-genics' order.pk %}" class="mr-3"><i class="fa fa-calendar" aria-hiddne="true"></i> Outlook</a>
                            <a href="{% url 'reservation:reservation-genics' order.pk %}" class="mr-3"><i class="fa fa-calendar" aria-hiddne="true"></i> Apple</a>
                            <a href="#" value="{{ order.pk }}" id="add-google" class="mr-3"><i class="fa fa-calendar" aria-hidden="true"></i> Google</a>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-3">分享活動</label>
                        <div class="col-9">
                            <!-- AddToAny BEGIN -->
                            <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
                                <!-- <a class="a2a_dd" href="https://www.addtoany.com/share"></a> -->
                                <a class="a2a_button_facebook"></a>
                                <a class="a2a_button_twitter"></a>
                                <a class="a2a_button_google_plus"></a>
                                <a class="a2a_button_line"></a>
                            </div>
                            <script>
                                var a2a_config = a2a_config || {};
                                a2a_config.locale = "zh-TW";
                            </script>
                            <script async src="https://static.addtoany.com/menu/page.js"></script>
                            <!-- AddToAny END -->
                        </div>
                    </div>
                </div>
            </div>
    </div> <!-- /#section -->
</div>

<script type="text/javascript">

    
    $( document ).ready(function() {
    
    /*
        $("#sendemail").on('click',function(){
            $.ajax({
                    url: "{% url 'reservation:reservation-send-email' order.pk %}",
                    success: function (response) {
                        if(response == "OK"){
                            //alert("Hello! I am an alert box!!");
                            $('.alert').replaceWith('<div class="alert alert-info col-12 mx-auto" role="alert">電子郵件確認信已寄出，請到您的信箱查看訊息並按下確認連結以完成預約確認動作。</div>')
                        }
                    }
                  });
        });
        
        $('#sendsms').on('click' , function(){
            $.ajax({
                url: "{% url 'reservation:reservation-send-sms' order.pk %}",
                success: function (response) {
                    if(response == "OK"){
                        //alert("Hello! I am an alert box!!");
                        $('.alert').replaceWith('<div class="alert alert-info col-12 mx-auto" role="alert">SMS確認信已寄出，請到您的信箱查看訊息並按下確認連結以完成預約確認動作。</div>')
                    }
                }
            });
        });
    */
        
    $('#add-google').on('click', function(){
            //console.log($(this).attr('value'));
            $.ajax({
                url: "/reservation/gen_google/" + $(this).attr('value') + "/",
                success:function(response){
                
                    href = "http://www.google.com/calendar/event?action=TEMPLATE&text=" + response.summary +  "&dates=";
                    href = href + response.start.dateTime + "/" + response.end.dateTime; 
                    href = href + "&details=相招來去裕隆導覽教育中心𨑨迌&location=367 苗栗縣三義鄉尖豐公路39-1號&trp=false&sprop=&sprop=name:";
                    
                    window.location.href = href;
                },
                error:function(error){
                    console.log('error');
                }
                
            })
            
    })
        
        
        
    });

</script>

{% endblock %}

YuLung/templates/order/validation_letter_sent.html
{% extends 'base.html' %}

{% block title %}確認信件/簡訊已寄出{% endblock %}

{% block meta %} 
{% endblock %}

{% block extraheader %}
{% endblock %}

{% block banner %}
{% endblock %}

{% block body %}
<div id="main" class="container my-3">
  <div id="section" class="row">
    <div class="col-12 col-lg-8 mx-auto">
      <div class="card p-3">
        <strong>確認信件/簡訊已寄出，請至你的電子郵件/手機簡訊查看，並點按內容連結以完成預約確認流程。</strong>
        <a href="#" class="btn btn-primary mx-auto px-5 mt-3" onclick="closeAndRefresh()" role="button">關閉視窗</a>
      </div>
    </div>
  </div>
</div>
<script>
  function closeAndRefresh() {
    opener.location.reload(); // or opener.location.href = opener.location.href;
    window.close(); // or self.close();
  }
</script>
{% endblock %}