YuLung/urls.py
from django.http import HttpResponse
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth import logout
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetCompleteView
)
from django.contrib.sitemaps.views import sitemap
from YuLung.sitemaps import StaticSitemap
from reservation.sitemaps import ServiceSitemap
from django.conf import settings
from django.conf.urls.static import static
from . import views

sitemaps = {
    'static': StaticSitemap,
    'service': ServiceSitemap
}

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^reservation/', include('reservation.urls')),
    re_path(r'^comments/$', views.Comments.as_view(), name='comments'),
    re_path(r'^my_reservation/$', views.MyReservation.as_view(), name='my_reservation'),
    re_path(r'^signin/$', views.SignIn.as_view(), name='sign-in'),
    re_path(r'^signup/$', views.SignUp.as_view(), name='sign-up'),
    re_path(r'^#_=_login/success/$', views.loginSuccess, name='login-success'),
    re_path(r'^login/success/$', views.loginSuccessRedirect, name='login-success-redirect'),
    re_path(r'^faq/$', views.FAQpage.as_view(), name='faq'),
    re_path(r'^privacy/$', views.privacy, name='privacy'),
    re_path(r'^tos/$', views.tos, name='tos'),
    re_path(r'^my/$', views.MyPage.as_view(), name='my'),
    re_path(r'^user/personalinfo/$',
            views.UserInfo.as_view(),
            name='user-profile'),
    re_path(r'^password/reset/$',
            views.PasswordReset.as_view(),
            name='front_password_reset'),
    re_path(r'^password_reset/done/$',
            PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
            name='front_password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.PasswordResetConfirm.as_view(),
            name='front_password_reset_confirm'),
    re_path(r'^reset/done/$',
            PasswordResetCompleteView.as_view(template_name='password_set_complete.html'),
            name='front_password_reset_complete'),
    re_path(r'^logou/$', logout, name='logout'),
    # Site Admin
    re_path(r'^site_admin/$', views.AdminIndex.as_view(), name='admin-index'),
    re_path(r'^site_admin/login/$', views.AdminSignIn.as_view(), name='admin-login'),
    re_path(r'^site_admin/logout/$', views.adminLogout, name='admin-logout'),
    re_path(r'^site_admin/info/banner/$', views.AdminBanner.as_view(), name='admin-banner'),
    re_path(r'^site_admin/password/reset/$',
            views.AdminPasswordReset.as_view(),
            name='password_reset'),
    re_path(r'^site_admin/password_reset/done/$',
            PasswordResetDoneView.as_view(template_name='admin_site/password_reset_done.html'),
            name='password_reset_done'),
    re_path(r'^site_admin/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.AdminPasswordResetConfirm.as_view(),
            name='password_reset_confirm'),
    re_path(r'^site_admin/reset/done/$',
            PasswordResetCompleteView.as_view(template_name='admin_site/password_set_complete.html'),
            name='password_reset_complete'),
    re_path(r'^site_admin/info/faq/$', views.AdminFAQ.as_view(), name='admin-faq'),
    re_path(r'^site_admin/info/faq/new/$', views.AdminFAQCreate.as_view(), name='admin-faq-create'),
    re_path(r'^site_admin/info/faq/(?P<pk>[0-9]+)/$',
            views.AdminFAQEdit.as_view(),
            name='admin-faq-edit'),
    re_path(r'^site_admin/info/faq/(?P<pk>[0-9]+)/delete/$',
            views.adminFAQDelete,
            name='admin-faq-delete'),
    re_path(r'^site_admin/info/settings/$', views.AdminSiteInfo.as_view(), name='admin-siteinfo'),
    re_path(r'^site_admin/info/seo/$', views.AdminSEO.as_view(), name='admin-seo'),
    re_path(r'^site_admin/info/email', views.AdminEmailTemplate.as_view(), name='admin-email'),
    re_path(r'^site_admin/service/course/$', views.AdminService.as_view(), name='admin-service'),
    re_path(r'^site_admin/service/course/new/$',
            views.AdminServiceCreate.as_view(),
            name='admin-service-create'),
    re_path(r'^site_admin/service/course/(?P<pk>[0-9]+)/$',
            views.AdminServiceEdit.as_view(),
            name='admin-service-edit'),
    re_path(r'^site_admin/service/course/(?P<pk>[0-9]+)/delete/$',
            views.adminServiceDelete,
            name='admin-service-delete'),
    re_path(r'^site_admin/service/customer/$', views.AdminCustomer.as_view(), name='admin-customer'),
    re_path(r'^site_admin/service/customer/new/$',
            views.AdminCustomerCreate.as_view(),
            name='admin-customer-create'),
    re_path(r'^site_admin/service/customer/(?P<pk>[0-9]+)/$',
            views.AdminCustomerEdit.as_view(),
            name='admin-customer-edit'),
    re_path(r'^site_admin/service/customer/(?P<pk>[0-9]+)/delete/$',
            views.adminCustomerDelete,
            name='admin-customer-delete'),
    re_path(r'^site_admin/calendar/$', views.AdminCalendar.as_view(), name='admin-calendar'),
    re_path(r'^site_admin/calendar/time_slot/$', views.AdminTimeSlot.as_view(), name='admin-timeslot'),
    re_path(r'^site_admin/calendar/time_slot/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$',
            views.AdminTimeSlot.as_view(),
            name='admin-timeslot-date'),
    re_path(r'^site_admin/calendar/time_slot/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/edit/(?P<pk>[0-9]+)/$',
            views.AdminTimeSlotEdit.as_view(),
            name='admin-timeslot-date-edit'),
    re_path(r'^site_admin/calendar/time_slot/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/delete/(?P<pk>[0-9]+)/$',
            views.adminTimeSlotDelete,
            name='admin-timeslot-date-delete'),
    re_path(r'^site_admin/order/$', views.AdminOrder.as_view(), name='admin-order'),
    re_path(r'^site_admin/ticket/$', views.AdminTicket.as_view(), name='admin-ticket'),
    re_path(r'^site_admin/comment/$', views.AdminComment.as_view(), name='admin-comment'),
    re_path(r'^site_admin/comment/(?P<pk>[0-9]+)/approve/$', views.adminCommentApprove, name='admin-comment-approve'),
    re_path(r'^site_admin/comment/(?P<pk>[0-9]+)/disapprove/$',
            views.adminCommentDisapprove,
            name='admin-comment-disapprove'),
    re_path(r'^site_admin/comment/(?P<pk>[0-9]+)/delete/$', views.adminCommentDelete, name='admin-comment-delete'),
    re_path(r'^site_admin/statistic/$', views.AdminStatistic.as_view(), name='admin-statistic'),
    re_path(r'^site_admin/data_export/$', views.AdminDataExport.as_view(), name='admin-data'),
    re_path(r'^site_admin/user_account/$', views.AdminUserAccount.as_view(), name='admin-user-account'),
    re_path(r'^site_admin/user_profile/$', views.AdmonUserProfile.as_view(), name='admin-user-profile'),
    re_path(r'^site_admin/user_permission/$', views.AdminUserPermission.as_view(), name='admin-user-permission'),
    # AJAX
    re_path(r'ajax/order/$', views.getOrderDetails, name='ajax-get-order'),
    re_path(r'ajax/ticket/$', views.getTicketDetails, name='ajax-get-ticket'),
    re_path(r'ajax/check_dayrender', views.check_adminDayRender, name='ajax-admin-dayrender'),
    re_path(r'ajax/get_user_ticket', views.adminGetUserTicket, name='ajax-admin-get-ticket'),
    re_path(r'ajax/search_ticket/$', views.adminSearchTicket, name='ajax-admin-search-ticket'),
    re_path(r'ajax/get_barchart/$', views.adminGetBarChart, name='ajax-admin-get-barchart'),
    re_path(r'ajax/get_piechart/$', views.adminGetPieChart, name='ajax-admin-get-piechart'),
    re_path(r'ajax/get_service_lines/$', views.adminGetLineChartService, name='ajax-admin-get-service-lines'),
    re_path(r'ajax/get_custerm_lines/$', views.adminGetLineChartCustomer, name='ajax-admin-get-customer-lines'),
    re_path(r'ajax/get_income_lines/$', views.adminGetLineChartIncome, name='ajax-admin-get-income-lines'),
    re_path(r'ajax/get_user/$', views.adminGetUserAccount, name='ajax-admin-get-user-account'),
    re_path(r'ajax/edit_user/$', views.adminUserAccountEdit, name='ajax-admin-user-account-edit'),
    re_path(r'ajax/del_user/$', views.adminUserAccountDelete, name='ajax-admin-user-account-del'),
    re_path(r'ajax/update_faq_order/$', views.adminUpdateFAQOrder, name='ajax-admin-update-faq-order'),
    re_path(r'ajax/get_record_count/$', views.adminGetRecordCount, name='ajax-admin-get-record-count'),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^googlee431d29ab682695b\.html$',
            lambda r: HttpResponse("google-site-verification: googlee431d29ab682695b.html", content_type="text/plain")),
    re_path(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: ", content_type="text/plain")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import re_path
from . import views

app_name = 'reservation'

urlpatterns = [
    re_path(r'^$', views.Reservation.as_view(), name='reservation-index'),
    re_path(r'^(?P<customer_pk>[0-9]+)/service/$', views.Service.as_view(), name='reservation-service'),
    re_path(r'^(?P<customer_pk>[0-9]+)/(?P<service_pk>[0-9]+)/date/$', views.Date.as_view(), name='reservation-date'),
    re_path(r'^(?P<customer_pk>[0-9]+)/(?P<service_pk>[0-9]+)/(?P<timeslot_pk>[0-9]+)/info/$',
            views.Info.as_view(),
            name='reservation-info'),
    re_path(r'^(?P<order_pk>[0-9]+)/confirm/$', views.Confirm.as_view(), name='reservation-confirm'),
    re_path(r'^(?P<order_pk>[0-9]+)/details/$', views.Confirm.as_view(), name='reservattion-order-details'),
    re_path(r'^service/(?P<service_pk>[0-9]+)/detail/$', views.ServiceDetail.as_view(), name='service-detail'),
    re_path(r'^cancelreservation/(?P<order_pk>[0-9]+)/$', views.cancel_reservation, name='reservation-cancel'),
    re_path(r'^site_admin/order/cancelreservation/(?P<order_pk>[0-9]+)/$',
            views.admin_cancel_reservation,
            name='admin-reservation-cancel'),
    re_path(r'^site_admin/order/ticket/cancelreservation/(?P<ticket_pk>[0-9]+)/$',
            views.admin_cancel_ticket_reservation,
            name='admin-ticket-reservation-cancel'),
    re_path(r'^sendvalidation_email/(?P<order_pk>[0-9]+)/$',
            views.send_validation_email,
            name='reservation-send-email'),
    re_path(r'^sendvalidation_sms/(?P<order_pk>[0-9]+)/$', views.send_validation_sms, name="reservation-send-sms"),
    re_path(r'^sendvalidation_success/$', views.send_validation_success, name='reservation-send-success'),
    re_path(r'^confirm_reservation/(?P<validation_key>[\w]+)/$',
            views.confirm_reservation,
            name='reservation-confirm-reservation'),
    re_path(r'^ajax/dayrender/', views.get_dayrender, name='ajax-dayrender'),
    re_path(r'^ajax/dayclick/', views.get_dayclick, name='ajax-dayclick'),
    re_path(r'^ajax/setinputperson/$', views.set_inputperson, name='ajax-inputperson'),
    re_path(r'^gen_ics/(?P<order_pk>[0-9]+)/$', views.GenICS(), name='reservation-genics'),
    re_path(r'^gen_google/(?P<order_pk>[0-9]+)/$', views.genGoogle, name='reservation-gengoogle')
]

YuLung/models.py
import os
from django.db import models
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.core.validators import MinValueValidator, MaxValueValidator, validate_email
from django.conf import settings
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from reservation.models import Orders

bannerfs = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'banners_image'))


class Banner(models.Model):
    banner_image = models.ImageField(upload_to='banners_image')
    banner_description = models.CharField(max_length=255)
    banner_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    title = models.CharField(max_length=255)
    content = models.CharField(max_length=1024)
    star = models.DecimalField(max_digits=2,
                               decimal_places=1,
                               validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    approve = models.BooleanField(default=False)
    active = models.BooleanField(default=False)

    def __unicode__(self):
        if(self.active):
            active = 'Active'
        else:
            active = 'Inactive'
        if len(self.content) > 20:
            content = self.content[0:20] + ' ...'
        else:
            content = self.content[:]
        return active + ' || ' + self.title + '-' + content


class FAQ(models.Model):
    question = models.CharField(max_length=1024)
    answer = RichTextField(max_length=1024)
    priority = models.DecimalField(max_digits=5, decimal_places=3)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    def __unicode__(self):
        if(self.active):
            active = 'Active'
        else:
            active = 'Inactive'
        if len(self.question) > 20:
            question = self.question[0:20] + '...'
        else:
            question = self.question[:]
        return active + ' || ' + question

    def get_absolute_url(self):
        return reverse('faq')


class SiteInfo(models.Model):
    site_info_content = RichTextField(max_length=1024)
    email = models.EmailField(validators=[validate_email])
    phone = models.CharField(max_length=16)
    address = models.CharField(max_length=255)


class Ticket(models.Model):
    assigned_by = models.ForeignKey(User, related_name='%(class)s_assigned_by', on_delete=models.CASCADE, null=True)
    assigned_to = models.ForeignKey(User, related_name='%(class)s_assigned_to', on_delete=models.CASCADE, null=True)
    order = models.ForeignKey(Orders, on_delete=models.CASCADE, null=True)
    finished = models.BooleanField(default=False)
    reported_customer_number = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(0)])
    create_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    reminder = models.TextField(max_length=2048, blank=True, default='')


class SEO(models.Model):
    title = models.CharField(max_length=1024, blank=True, default='')
    url_address = models.URLField(null=True)
    description = models.CharField(max_length=1024, blank=True, default='')
    img = models.ImageField(upload_to='seo_image', blank=True, default='')
    type = models.CharField(default='website', max_length=1024)


class EmailTemplate(models.Model):
    from_email = models.EmailField()
    subject = models.CharField(max_length=1024)
    email_content = models.TextField(max_length=2048)

YuLung/templates/index/index.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% block title %}首頁{% endblock %}

{% block meta %}
  <meta property="og:url" content="{{ seo.url_address }}" />
    <meta property="og:title" content="{{ seo.title }}" />
    <meta property="og:description" content="{{ seo.description }}" />
    <meta property="og:image" content="{{ base_url }}{{ seo.img.url }}" />
    <meta property="og:type" content="{{ seo.type }}" />
    <meta name="twitter.card" content="{{ seo.description }}" />
{% endblock %}

{% block extraheader %}
{% endblock %}

{% block quickmenu %}
<div id="quick-menu" class="text-center mb-5">
  <a id="reservation" class="btn btn-success btn-lg" href="{% url 'reservation:reservation-index' %}#main">預約參觀
    <i class="fa fa-check" aria-hidden="true"></i>
  </a>
</div>
{% endblock %}

{% block body %}
<div id="main" class="container mb-3">
  <div class="row mb-5 py-3">
    {% include 'index/index_welcome.html' %}
    {% include 'index/index_calendar.html' %} 
  </div>
  <div class="row py-3">
    {% include 'index/index_contact.html' %}
    {% include 'index/index_map.html' %}
  </div>
</div>
<!-- /#main -->
{% endblock %}

YuLung/templates/index/index_calendar.html
<div class="col-lg-6 col-sm-12 mb-3 mb-lg-0">
  <div class="heading d-flex justify-content-between mb-3">
    <h4 class="d-inline-flex pb-2">即時預約概況</h4>
    <div class="small" style="margin-top: -25px;">
      <div class="text-success"><span class="fc-event-dot fc-event-slot-empty"></span> 為尚可預約</div>
      <div class="text-danger"><span class="fc-event-dot fc-event-slot-full"></span> 為預約已滿</div>
      <div class="text-muted">灰色為非營業日或已過可預約期限</div>
    </div>
  </div>
  <div class="content">
    <div id="factoryCalendar" class="shadow rounded"></div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  var popOverPlacement = 'e';
  var popOverSmartPlacement = false;
  // device detection
  if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|ipad|iris|kindle|Android|Silk|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(navigator.userAgent) 
    || /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0,4))) { 
      popOverPlacement = 'n';
      popOverSmartPlacement = true;
  }

  var eventInfo = [];
  $('#factoryCalendar').fullCalendar({
    locale: 'zh-tw',
    header: {
      left: 'prev',
      center: 'title',
      right: 'next',
    },
    titleFormat: 'YYYY/MM',
    firstDay: 1,
    fixedWeekCount: false,
    height: 'auto',
    dayRender: function (date, cell) {
      $.ajax({
        method: 'GET',
        url: "{% url 'reservation:ajax-dayrender'%}",
        data: { 'date': date.format() },
        success: function (response) {
          if (response == "NO TIME SLOT") {
            //cell.append("<span class='fc-event-holiday'></span>");
            $(".fc .fc-row .fc-content-skeleton td[data-date='" + date.format() + "']").css("opacity", "0.3");
          }
          else if (response == "OUTDATED") {
            //cell.css("background-color" , "blue");
            $(".fc .fc-row .fc-content-skeleton td[data-date='" + date.format() + "']").css("opacity", "0.3");
          }
          else {
            //cell.css("background-color", "#ffc107");
            var dayInfo = [];
            $.each(response.event, function(index, value) {
              var content = '';
              var capacity = '';
              if (this.capacity > 0) {
                if (typeof this.title === 'undefined') {
                  capacity = 'empty';
                  content = this.time + ' <a href="/reservation#main">可預約</a>';
                } else {
                  capacity = 'occupy';
                  content = this.time + ' 可預約 (推薦<a href="/reservation/' + this.cid + '/' + this.id + '/date/#main?date=' + this.date + '">' + this.title + '</a>)';
                }
              } else {
                capacity = 'full';
                content = '預約已滿';
              }
              cell.append('<div class="slot-' + index + ' fc-event-dot fc-event-slot-' + capacity + '"></div>');
              dayInfo.push({ 'content': content }); 
            });
            eventInfo[date.format()] = dayInfo;
          }
        }
      });
    },
    eventAfterAllRender: function() {
      $('td.fc-day-top').on({
        powerTipPreRender: function() {
          var todayContent = eventInfo[$(this).attr('data-date')];
          var popOverContent = '';
          $.each(todayContent, function(index) {
            if (index != (length - 1)) {
              popOverContent += this.content + '<br />';
            } else {
              popOverContent += this.content;
            }
          });
          $(this).data('powertip', popOverContent);
          //console.log(popOverContent);
        }
      });
      $('td.fc-day-top').powerTip({
        mouseOnToPopup: true,
        placement: popOverPlacement,
        smartPlacement: popOverSmartPlacement,
        closeDelay: 300
      });
    }
  });
});
</script>

YuLung/templates/index/index_contact.html
<div class="col-lg-4 col-sm-12 mb-3 mb-lg-0">
  <div class="heading mb-3">
    <h4 class="d-inline-flex pb-2">聯絡我們</h4>
  </div>
  <div class="content">
    <div class="email row p-2">
      <i class="fa fa-envelope-o fa-lg col-2 text-center" aria-hidden="true"></i><a href="mailto:{{site_info.email}}">{{site_info.email}}</a>
    </div>
    <div class="phone row p-2">
      <i class="fa fa-phone fa-lg col-2 text-center" aria-hidden="true"></i>{{site_info.phone}}
    </div>
    <div class="address row p-2">
      <i class="fa fa-map-marker fa-lg col-2 text-center" aria-hidden="true"></i><address class="d-inline">{{site_info.address}}</address>
    </div>
    <div class="social-web row p-2">
      <span class="facebook col">
        <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FYulonEC&tabs=timeline&width=340&height=130&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId=294797807684724" width="340" height="130" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
        </iframe>
      </span>
    </div>
  </div>
</div>

YuLung/templates/index/index_map.html
<!--Map-->
<div class="col-lg-8 col-sm-12 mb-3 mb-lg-0">
  <div class="content">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3633.864612367263!2d120.74986921437126!3d24.38601277011544!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x346905c962535277%3A0x65ab8abc404fa194!2z6KOV6ZqG5rG96LuK6KO96YCg6IKh5Lu95pyJ6ZmQ5YWs5Y-4!5e0!3m2!1szh-TW!2stw!4v1507506900602" width="100%" height="350px" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

YuLung/templates/index/index_welcome.html
<div class="col-lg-6 col-sm-12 mb-3 mb-lg-0">
  <div class="heading mb-3">
    <h4 class="d-inline-flex pb-2">車之道體驗中心</h4>
  </div>
  <div class="content">
    <p>{{site_info.site_info_content|safe}}</p>
  </div>
  <div>
    <a class="btn btn-primary px-5 mx-1" href="{% url 'reservation:reservation-index' %}#main">預約參觀</a>
    <a class="btn btn-success px-5 mx-1" href="{% url 'faq' %}">常見問題</a>
  </div>
</div>