YuLung/urls.py
from django.http import HttpResponse
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth import logout
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetCompleteView
)
from django.contrib.sitemaps.views import sitemap
from YuLung.sitemaps import StaticSitemap
from reservation.sitemaps import ServiceSitemap
from django.conf import settings
from django.conf.urls.static import static
from . import views

sitemaps = {
    'static': StaticSitemap,
    'service': ServiceSitemap
}

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^reservation/', include('reservation.urls')),
    re_path(r'^comments/$', views.Comments.as_view(), name='comments'),
    re_path(r'^my_reservation/$', views.MyReservation.as_view(), name='my_reservation'),
    re_path(r'^signin/$', views.SignIn.as_view(), name='sign-in'),
    re_path(r'^signup/$', views.SignUp.as_view(), name='sign-up'),
    re_path(r'^#_=_login/success/$', views.loginSuccess, name='login-success'),
    re_path(r'^login/success/$', views.loginSuccessRedirect, name='login-success-redirect'),
    re_path(r'^faq/$', views.FAQpage.as_view(), name='faq'),
    re_path(r'^privacy/$', views.privacy, name='privacy'),
    re_path(r'^tos/$', views.tos, name='tos'),
    re_path(r'^my/$', views.MyPage.as_view(), name='my'),
    re_path(r'^user/personalinfo/$',
            views.UserInfo.as_view(),
            name='user-profile'),
    re_path(r'^password/reset/$',
            views.PasswordReset.as_view(),
            name='front_password_reset'),
    re_path(r'^password_reset/done/$',
            PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
            name='front_password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.PasswordResetConfirm.as_view(),
            name='front_password_reset_confirm'),
    re_path(r'^reset/done/$',
            PasswordResetCompleteView.as_view(template_name='password_set_complete.html'),
            name='front_password_reset_complete'),
    re_path(r'^logou/$', logout, name='logout'),
    # Site Admin
    re_path(r'^site_admin/$', views.AdminIndex.as_view(), name='admin-index'),
    re_path(r'^site_admin/login/$', views.AdminSignIn.as_view(), name='admin-login'),
    re_path(r'^site_admin/logout/$', views.adminLogout, name='admin-logout'),
    re_path(r'^site_admin/info/banner/$', views.AdminBanner.as_view(), name='admin-banner'),
    re_path(r'^site_admin/password/reset/$',
            views.AdminPasswordReset.as_view(),
            name='password_reset'),
    re_path(r'^site_admin/password_reset/done/$',
            PasswordResetDoneView.as_view(template_name='admin_site/password_reset_done.html'),
            name='password_reset_done'),
    re_path(r'^site_admin/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.AdminPasswordResetConfirm.as_view(),
            name='password_reset_confirm'),
    re_path(r'^site_admin/reset/done/$',
            PasswordResetCompleteView.as_view(template_name='admin_site/password_set_complete.html'),
            name='password_reset_complete'),
    re_path(r'^site_admin/info/faq/$', views.AdminFAQ.as_view(), name='admin-faq'),
    re_path(r'^site_admin/info/faq/new/$', views.AdminFAQCreate.as_view(), name='admin-faq-create'),
    re_path(r'^site_admin/info/faq/(?P<pk>[0-9]+)/$',
            views.AdminFAQEdit.as_view(),
            name='admin-faq-edit'),
    re_path(r'^site_admin/info/faq/(?P<pk>[0-9]+)/delete/$',
            views.adminFAQDelete,
            name='admin-faq-delete'),
    re_path(r'^site_admin/info/settings/$', views.AdminSiteInfo.as_view(), name='admin-siteinfo'),
    re_path(r'^site_admin/info/seo/$', views.AdminSEO.as_view(), name='admin-seo'),
    re_path(r'^site_admin/info/email', views.AdminEmailTemplate.as_view(), name='admin-email'),
    re_path(r'^site_admin/service/course/$', views.AdminService.as_view(), name='admin-service'),
    re_path(r'^site_admin/service/course/new/$',
            views.AdminServiceCreate.as_view(),
            name='admin-service-create'),
    re_path(r'^site_admin/service/course/(?P<pk>[0-9]+)/$',
            views.AdminServiceEdit.as_view(),
            name='admin-service-edit'),
    re_path(r'^site_admin/service/course/(?P<pk>[0-9]+)/delete/$',
            views.adminServiceDelete,
            name='admin-service-delete'),
    re_path(r'^site_admin/service/customer/$', views.AdminCustomer.as_view(), name='admin-customer'),
    re_path(r'^site_admin/service/customer/new/$',
            views.AdminCustomerCreate.as_view(),
            name='admin-customer-create'),
    re_path(r'^site_admin/service/customer/(?P<pk>[0-9]+)/$',
            views.AdminCustomerEdit.as_view(),
            name='admin-customer-edit'),
    re_path(r'^site_admin/service/customer/(?P<pk>[0-9]+)/delete/$',
            views.adminCustomerDelete,
            name='admin-customer-delete'),
    re_path(r'^site_admin/calendar/$', views.AdminCalendar.as_view(), name='admin-calendar'),
    re_path(r'^site_admin/calendar/time_slot/$', views.AdminTimeSlot.as_view(), name='admin-timeslot'),
    re_path(r'^site_admin/calendar/time_slot/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$',
            views.AdminTimeSlot.as_view(),
            name='admin-timeslot-date'),
    re_path(r'^site_admin/calendar/time_slot/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/edit/(?P<pk>[0-9]+)/$',
            views.AdminTimeSlotEdit.as_view(),
            name='admin-timeslot-date-edit'),
    re_path(r'^site_admin/calendar/time_slot/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/delete/(?P<pk>[0-9]+)/$',
            views.adminTimeSlotDelete,
            name='admin-timeslot-date-delete'),
    re_path(r'^site_admin/order/$', views.AdminOrder.as_view(), name='admin-order'),
    re_path(r'^site_admin/ticket/$', views.AdminTicket.as_view(), name='admin-ticket'),
    re_path(r'^site_admin/comment/$', views.AdminComment.as_view(), name='admin-comment'),
    re_path(r'^site_admin/comment/(?P<pk>[0-9]+)/approve/$', views.adminCommentApprove, name='admin-comment-approve'),
    re_path(r'^site_admin/comment/(?P<pk>[0-9]+)/disapprove/$',
            views.adminCommentDisapprove,
            name='admin-comment-disapprove'),
    re_path(r'^site_admin/comment/(?P<pk>[0-9]+)/delete/$', views.adminCommentDelete, name='admin-comment-delete'),
    re_path(r'^site_admin/statistic/$', views.AdminStatistic.as_view(), name='admin-statistic'),
    re_path(r'^site_admin/data_export/$', views.AdminDataExport.as_view(), name='admin-data'),
    re_path(r'^site_admin/user_account/$', views.AdminUserAccount.as_view(), name='admin-user-account'),
    re_path(r'^site_admin/user_profile/$', views.AdmonUserProfile.as_view(), name='admin-user-profile'),
    re_path(r'^site_admin/user_permission/$', views.AdminUserPermission.as_view(), name='admin-user-permission'),
    # AJAX
    re_path(r'ajax/order/$', views.getOrderDetails, name='ajax-get-order'),
    re_path(r'ajax/ticket/$', views.getTicketDetails, name='ajax-get-ticket'),
    re_path(r'ajax/check_dayrender', views.check_adminDayRender, name='ajax-admin-dayrender'),
    re_path(r'ajax/get_user_ticket', views.adminGetUserTicket, name='ajax-admin-get-ticket'),
    re_path(r'ajax/search_ticket/$', views.adminSearchTicket, name='ajax-admin-search-ticket'),
    re_path(r'ajax/get_barchart/$', views.adminGetBarChart, name='ajax-admin-get-barchart'),
    re_path(r'ajax/get_piechart/$', views.adminGetPieChart, name='ajax-admin-get-piechart'),
    re_path(r'ajax/get_service_lines/$', views.adminGetLineChartService, name='ajax-admin-get-service-lines'),
    re_path(r'ajax/get_custerm_lines/$', views.adminGetLineChartCustomer, name='ajax-admin-get-customer-lines'),
    re_path(r'ajax/get_income_lines/$', views.adminGetLineChartIncome, name='ajax-admin-get-income-lines'),
    re_path(r'ajax/get_user/$', views.adminGetUserAccount, name='ajax-admin-get-user-account'),
    re_path(r'ajax/edit_user/$', views.adminUserAccountEdit, name='ajax-admin-user-account-edit'),
    re_path(r'ajax/del_user/$', views.adminUserAccountDelete, name='ajax-admin-user-account-del'),
    re_path(r'ajax/update_faq_order/$', views.adminUpdateFAQOrder, name='ajax-admin-update-faq-order'),
    re_path(r'ajax/get_record_count/$', views.adminGetRecordCount, name='ajax-admin-get-record-count'),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^googlee431d29ab682695b\.html$',
            lambda r: HttpResponse("google-site-verification: googlee431d29ab682695b.html", content_type="text/plain")),
    re_path(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: ", content_type="text/plain")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

YuLung/models.py
import os
from django.db import models
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.core.validators import MinValueValidator, MaxValueValidator, validate_email
from django.conf import settings
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from reservation.models import Orders

bannerfs = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'banners_image'))


class Banner(models.Model):
    banner_image = models.ImageField(upload_to='banners_image')
    banner_description = models.CharField(max_length=255)
    banner_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    title = models.CharField(max_length=255)
    content = models.CharField(max_length=1024)
    star = models.DecimalField(max_digits=2,
                               decimal_places=1,
                               validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    approve = models.BooleanField(default=False)
    active = models.BooleanField(default=False)

    def __unicode__(self):
        if(self.active):
            active = 'Active'
        else:
            active = 'Inactive'
        if len(self.content) > 20:
            content = self.content[0:20] + ' ...'
        else:
            content = self.content[:]
        return active + ' || ' + self.title + '-' + content


class FAQ(models.Model):
    question = models.CharField(max_length=1024)
    answer = RichTextField(max_length=1024)
    priority = models.DecimalField(max_digits=5, decimal_places=3)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    def __unicode__(self):
        if(self.active):
            active = 'Active'
        else:
            active = 'Inactive'
        if len(self.question) > 20:
            question = self.question[0:20] + '...'
        else:
            question = self.question[:]
        return active + ' || ' + question

    def get_absolute_url(self):
        return reverse('faq')


class SiteInfo(models.Model):
    site_info_content = RichTextField(max_length=1024)
    email = models.EmailField(validators=[validate_email])
    phone = models.CharField(max_length=16)
    address = models.CharField(max_length=255)


class Ticket(models.Model):
    assigned_by = models.ForeignKey(User, related_name='%(class)s_assigned_by', on_delete=models.CASCADE, null=True)
    assigned_to = models.ForeignKey(User, related_name='%(class)s_assigned_to', on_delete=models.CASCADE, null=True)
    order = models.ForeignKey(Orders, on_delete=models.CASCADE, null=True)
    finished = models.BooleanField(default=False)
    reported_customer_number = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(0)])
    create_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    reminder = models.TextField(max_length=2048, blank=True, default='')


class SEO(models.Model):
    title = models.CharField(max_length=1024, blank=True, default='')
    url_address = models.URLField(null=True)
    description = models.CharField(max_length=1024, blank=True, default='')
    img = models.ImageField(upload_to='seo_image', blank=True, default='')
    type = models.CharField(default='website', max_length=1024)


class EmailTemplate(models.Model):
    from_email = models.EmailField()
    subject = models.CharField(max_length=1024)
    email_content = models.TextField(max_length=2048)

YuLung/templates/admin_site/info/basic_banner.html
{% extends 'admin_site/base.html' %}

{% block title %}橫幅圖管理{% endblock %}

{% block meta%}
{% endblock %}

{% block extraheader%}
{% endblock%}

{% block body %}
<h3 class="page-heading mb-4">
  橫幅圖管理
  <a class="btn btn-warning float-right" href="{% url 'index' %}" target="_blank" role="button">
    瀏覽首頁
  </a>
</h3>
<div class="row mb-2">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <h5 class="card-title">預覽橫幅圖</h5>
          <p class="text-muted mb-4">
            <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>目前使用的橫幅圖
          </p>
          <img class="img-fluid" src="{{banner.banner_image.url}}" alt="{{ banner.banner_description }}" />

          <hr class="my-5" />
          <h5 class="card-title">上傳橫幅圖</h5>
          <p class="text-muted mb-4">
            <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>上傳新的橫幅圖
          </p>
          {% for field in form%}
            <div class="form-group row">
              <label for="name" class="col-2 col-form-label">{{field.label_tag}}</label>
              <div class="col">
                {{ field }}
              </div>
            </div>
            {% endfor %}
          <div class="form-group">
            {% include 'admin_site/button/submit.html' %} 
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

YuLung/templates/admin_site/info/basic_email.html
{% extends 'admin_site/base.html' %}

{% block title %}編輯確認信內容{% endblock %}

{% block meta%}
{% endblock %}

{% block extraheader%}
{% endblock%}

{% block body %}
<div class="row">
    {% include 'admin_site/info/email_template_form.html' %}
</div>
{% endblock %}


YuLung/templates/admin_site/info/basic_faq.html
{% extends 'admin_site/base.html' %}

{% block title %}常見問題管理{% endblock %}

{% block meta%}
{% endblock %}

{% block extraheader%}
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
{% endblock%}

{% block body %}
<h3 class="page-heading mb-4">
  常見問題管理
  <a class="btn btn-warning float-right" href="{% url 'faq' %}" target="_blank" role="button">
    瀏覽常見問題頁
  </a>
</h3>
<div class="row mb-2">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          常見問題列表
          <a id="btn-add" class="btn btn-primary float-right" href="{% url 'admin-faq-create' %}" role="button">
            <i class="fa fa-plus" aria-hidden="true"></i>新增
          </a>
          <button id="btn-update-order" class="btn btn-primary float-right mx-2">更改排序</button>
        </h5>
        <p class="text-muted mb-4">
          <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>請直接編輯/刪除問題，或按右側的「新增」鈕新增問題，拖拉可更改排序，確認排序後點按右側的「更改排序」鈕更改排序
        </p>
        <label id="update-success" class="text-success text-center mx-auto alert alert-success col d-none"></label>
        <div class="table-responsive">
          <table class="table center-aligned-table table-hover">
            <thead>
              <tr class="text-primary">
                <th class="col-1">#</th>
                <th class="col-3">問題</th>
                <th class="col-5">答案</th>
                <th class="col-1">啟用?</th>
                <th class="col-1"></th>
                <th class="col-1"></th>
              </tr>
            </thead>
            <tbody id="sortable">
              {% load permission_tags %}
              {% for faq in faq_list %}
              <tr value="{{faq.pk}}">
                <td></td>
                <td>{{faq.question}}</td>
                <td>{{faq.answer|safe}}</td>
                <td>{{faq.active}}</td>
                <td>
                  {% if request.user|can:'edit_site_admin' %}
                  <a href="{% url 'admin-faq-edit' faq.pk %}" class="btn btn-primary btn-sm">編輯</a>
                  {% endif %}
                </td>
                <td>
                  {% if request.user|can:'edit_site_admin' %}
                  <a href="{% url 'admin-faq-delete' faq.pk %}" class="btn btn-danger btn-sm">刪除</a>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    
    $(document).ready(function () {
        
        var faqOrder = null;
        
        $("#sortable").sortable({
            update: function(event, ui) {
                        //console.log($(this).sortable('toArray', {attribute: 'value'}));
                        faqOrder = $(this).sortable('toArray', {attribute: 'value'});
                    }
        });
        $("#sortable").disableSelection();
        
        $("#btn-update-order").click(function(){
            
            //console.log(faqOrder);
            if (faqOrder){
                $.ajax({
                    url:"{% url 'ajax-admin-update-faq-order' %}",
                    data:{"faqOrder":faqOrder},
                    success:function(response){
                        
                        if (response == "success"){
                            console.log(response);
                            $("#update-success").text("更新成功");
                            $('#update-success').removeClass('d-none');
                        }
                    }
                });
            }
        });
        
    });

</script>
{% endblock %}

YuLung/templates/admin_site/info/basic_info.html
{% extends 'admin_site/base.html' %}

{% block title %}公司資訊{% endblock %}

{% block meta%}
{% endblock %}

{% block extraheader%}
{% endblock%}

{% block body %}
<h3 class="page-heading mb-4">
  公司資訊
  <a class="btn btn-warning float-right" href="{% url 'index' %}" target="_blank" role="button">
    瀏覽首頁
  </a>
</h3>
<div class="row mb-2">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <h5 class="card-title">簡介說明</h5>
          <p class="text-muted mb-4">
            <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>首頁中間區塊說明資訊
          </p>
          {{ form.site_info_content | safe }}

          <hr class="my-5" />
          <h5 class="card-title">聯絡我們</h5>
          <p class="text-muted mb-4">
            <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>首頁右側區塊說明資訊
          </p>
          <div class="form-group row">
            <label for="id_email" class="col-2 col-form-label">Email: </label>
            <div class="col">
              {{form.email}}
            </div>
          </div>
          <div class="form-group row">
            <label for="id_phone" class="col-2 col-form-label">電話: </label>
            <div class="col">
              {{form.phone}}
            </div>
          </div>
          <div class="form-group row">
            <label for="id_address" class="col-2 col-form-label">地址: </label>
            <div class="col">
              {{form.address}}
            </div>
          </div>
          <div class="form-group">
            {% include 'admin_site/button/submit.html' %} 
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

YuLung/templates/admin_site/info/basic_seo.html
{% extends 'admin_site/base.html' %}

{% block title %}搜尋引擎優化{% endblock %}

{% block meta%}
{% endblock %}

{% block extraheader%}
{% endblock%}

{% block body %}
<h3 class="page-heading mb-4">
  搜尋引擎優化
  <a class="btn btn-warning float-right" href="{% url 'index' %}" target="_blank" role="button">
    瀏覽首頁
  </a>
</h3>
<div class="row mb-2">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <h5 class="card-title">搜尋引擎優化設定</h5>
          <p class="text-muted mb-4">
            <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>搜尋結果摘要資訊的優化調整
          </p>
          <div class="form-group row">
            <label for="title" class="col-2 col-form-label">標題: </label>
            <div class="col">
              {{form.title}}
              <p class="text-muted mb-4">
                <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>
                <strong>預設的網頁標題</strong>。此設定只對首頁有效，其他頁面會以該頁面標題為網頁標題。
              </p>
            </div>
          </div>
          <div class="form-group row">
            <label for="description" class="col-2 col-form-label">說明: </label>
            <div class="col">
              {{form.description}}
              <p class="text-muted mb-4">
                <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>
                <strong>預設的描述說明</strong>。此設定只對首頁有效，其他頁面會自動擷取網頁內容當做描述說明。
              </p>
            </div>
          </div>
          <div class="form-group row">
            <label for="url" class="col-2 col-form-label">網址: </label>
            <div class="col">
              {{form.url_address}}
              <p class="text-muted mb-4">
                <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>
                <strong>預設的網站網址</strong>。此設定只對首頁有效，其他頁面會顯示該頁面的網址。
              </p>
            </div>
          </div>
          <div class="form-group row">
            <label for="thumbnail" class="col-2 col-form-label">代表圖片: </label>
            <div class="col">
              <div class="row">
                <div class="col-2">
                  <img src="{{form.instance.img.url}}" style="height: 200px; width: auto;" />
                </div>
                <div class="col">
                  {{form.img}}
                </div>
              </div>
              <p class="text-muted mb-4">
                <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>
                <strong>預設的代表圖片</strong>。此設定對全部網頁有效，此圖片將顯示在搜尋結果的預覽圖片及 Facebook 分享連結的預覽圖片。
              </p>
            </div>
          </div>
          <div class="form-group row">
            <label for="type" class="col-2 col-form-label">網站類型: </label>
            <div class="col">
              {{form.type}}
              <p class="text-muted mb-4">
                <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i>
                <strong>預設的網站類型</strong>。此設定對全部網頁有效，預設值為「website」（其他可供使用的還有 article、book、profile、music、video 等類型）。
              </p>
            </div>
          </div>
          <div class="form-group">
            {% include 'admin_site/button/submit.html' %}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

YuLung/templates/admin_site/info/del_faq_renderer.html
  <div class="col-md-6 col-sm-12">
    <div class="card my-3">
      <div class="card-header">
        <h4 class="card-title">常見問題列表                
        <span>
        {% if edit %}
            <button id="btn-add" class="btn btn-primary btn-sm float-right" href="{% url 'admin-faq' %}" role="button">
            <i class="fa fa-plus" aria-hidden="true"></i>新增</button>
        {% else %}
            <button id="btn-add" class="btn btn-primary btn-sm float-right" href="" role="button">
            <i class="fa fa-plus" aria-hidden="true"></i>新增</button>
        {% endif %}
        </span>
        </h4>
      </div>
      <div class="card-body">
        {% for faq in faq_list %}

        <div class="row">
          <a class="btn btn-light col-11 text-left " data-toggle="collapse" href="#faq{{faq.pk}}" aria-expanded="false" aria-controls="faq{{faq.pk}}">
            {{faq.question}}
            <a href="{% url 'admin-faq-edit' faq.pk %}" class="btn btn-outline-secondary col-1" role="button">
              <i class="fa fa-pencil" aria-hidden="true"></i>
            </a>
          </a>

          <div class="collapse col-12 px-1" id="faq{{faq.pk}}">
            <table class="table-sm table">
              <tbody class="row">
                <tr class="col-12">
                    <th scope="row" class="col-3">Answer</th>
                    <td>
                        <div>{{faq.answer|safe}}</div>
                    </td>
                </tr>
                <tr class="col-12">
                    <th scope="row" class="col-3">Priority</th>
                    <td>{{faq.priority}}</td>
                </tr>
                <tr class="col-12">
                    <th scope="row" class="col-3">Active</th>
                    <td>{{faq.active}}</td>
                </tr>
                
              </tbody>
            </table>
          </div>
        </div>

        {% endfor %}
      </div>
    </div>
  </div>

YuLung/templates/admin_site/info/del_seo_form.html
<!DOCTYPE html>

<form enctype="multipart/form-data" method="post">
    {% csrf_token %}

    <div class="form-group">
      <label for="title">標題</label>
      <small>* 預設的網頁標題。此設定只對首頁有效，其他頁面會顯示該頁面的標題。</small>
      {{form.title}}
    </div>

    <div class="form-group">
      <label for="url">網址</label>
      <small>* 預設的網站網址。此設定只對首頁有效，其他頁面會顯示該頁面的網址。</small>
      {{form.url_address}}
    </div>

    <div class="form-group">
      <label for="description">說明</label>
      <small>* 預設的描述說明。此設定只對首頁有效，其他頁面會自動擷取網頁內容片段當做描述說明。</small>
      {{form.description}}
    </div>

    <div class="form-group">
      <label for="thumbnail">代表圖片</label>
      <small>* 預設的代表圖片。此設定對全部網頁有效，此圖片將顯示在搜尋結果的預覽圖片及 Facebook 分享連結的預覽圖片。</small>
      <br>
      <img src="{{form.instance.img.url}}"></img>
      {{form.img}}
    </div>

    <div class="form-group">
      <label for="type">網站類型</label>
      <small>* 預設的網站類型。此設定對全部網頁有效，預設值為「website」（其他可供使用的還有 article、book、profile、music、video 等類型）。</small>
      {{form.type}}
    </div>

    <div class="row">
        <button type="submit" class="btn btn-outline-info float-right col-12">送出</button>
        
        <!--<i class="fa fa-trash-o" aria-hidden="true"></i>刪除</a>-->
    </div>
</form>